name: Check Directory Changes

on:
  pull_request:
    branches:
      - main

jobs:
  check-changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check for directory changes
        id: check_changes
        run: |
          # Change this to the directory you want to monitor
          DIR="../../src/resources"

          # Get the list of changed files in the specified directory
          CHANGED_FILES=$(git diff --name-only ${{ github.base_ref }}...${{ github.head_ref }} -- $DIR)

          # Check if there are changes in the specified directory
          if [ -n "$CHANGED_FILES" ]; then
            echo "Changes detected in $DIR"
            echo "$CHANGED_FILES"
            echo "::set-output name=changes::true"
          else
            echo "No changes detected in $DIR"
            echo "::set-output name=changes::false"
          fi

      - name: Use the output
        run: |
          if [ "${{ steps.check_changes.outputs.changes }}" == "true" ]; then
            # Add your actions here if changes are detected
            echo "Changes detected, take necessary actions..."
          else
            echo "No changes detected."
          fi
