name: Enforce Reviewers for Directory Changes

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  enforce-reviewers:
    runs-on: ubuntu-latest
    steps:
      - name: Check if directory changed
        id: check_directory
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          path: changed_files

      - name: Set reviewers based on directory changes
        id: set_reviewers
        run: |
          changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})

          if echo "$changed_files" | grep -q "^directory1/"; then
            echo "Directory 1 changed"
            reviewers="user1 user2"
          elif echo "$changed_files" | grep -q "^directory2/"; then
            echo "Directory 2 changed"
            reviewers="user3 user4"
          else
            echo "No specific directory changed"
            reviewers=""
          fi

          echo "::set-output name=reviewers::$reviewers"

      - name: Request Reviews
        if: steps.set_reviewers.outputs.reviewers != ''
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: branches } = await github.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
            });

            const reviewers = "${{ steps.set_reviewers.outputs.reviewers }}".split(" ");
            echo "$reviewers"
            await github.pulls.requestReviewers({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              reviewers: reviewers,
            });
