name: Merge Restrictions

on:
  pull_request:
    branches:
      - main

jobs:
  check-changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get changed directory
        id: check_directory_changes
        uses: tj-actions/changed-files@v43
        with:
          files_yaml: |
            src_resources:
              - src/resources/**
              - src/json/**

      - name: Run step if resources files in changed
        id: define_resources_reviewers_by_directory
        if: steps.check_directory_changes.outputs.src_resources_any_changed == 'true'
        env:
          RESOURCES_CHANGED_FILES: ${{ steps.check_directory_changes.outputs.src_resources_all_changed_files }}
          REVIEWERS: ""
        run: |
          echo "One or more files in the resources folder has changed."
          echo "List all the files that have changed: $RESOURCES_CHANGED_FILES"
          
          if echo "$RESOURCES_CHANGED_FILES" | grep -q "src/resources"; then
            echo "src resources changed"
            REVIEWERS="user1,user2"
          fi
          
          if echo "$RESOURCES_CHANGED_FILES" | grep -q "src/json"; then
            echo "src json changed"
            if echo "$REVIEWERS" == ''; then
              REVIEWERS="user3,user4"
            else
              REVIEWERS="$REVIEWERS,user3,user4"
            fi
          fi
          
          echo "$REVIEWERS reviewers"
          echo "reviewers=$REVIEWERS" >> "$GITHUB_OUTPUT"

      - name: Run step if any test folder changed
        id: define_test_reviewers_by_directory
        if: steps.check_directory_changes.outputs.test_any_changed == 'true'
        env:
          TEST_ALL_CHANGED_FILES: ${{ steps.check_directory_changes.outputs.test_all_changed_files }}
          REVIEWERS: "azamatus user1 user2"
        run: |
          echo "One or more files in the test folder has changed."
          echo "List all the files that have changed: $TEST_ALL_CHANGED_FILES"
       
          echo "$REVIEWERS reviewers"
          echo "reviewers=$REVIEWERS" >> "$GITHUB_OUTPUT"    

      - name: Add reviewers if specific directory changes detected
        if: |
          steps.define_resources_reviewers_by_directory.outputs.reviewers != '' || steps.define_test_reviewers_by_directory.outputs.reviewers != ''
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.MY_PAT }}
          script: |
            const { data: branches } = await github.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
            });
            
            const author = "${{ github.event.pull_request.user.login }}";

            const resourcesReviewers = "${{ steps.define_resources_reviewers_by_directory.outputs.reviewers }}".split(",");
            const testReviewers = "${{ steps.define_test_reviewers_by_directory.outputs.reviewers }}".split(",");
            
            console.log(resourcesReviewers, "resourcesReviewers");
            console.log(testReviewers, "testReviewers");
            
            const reviewers = [...new Set([...resourcesReviewers, ...testReviewers])];
            console.log(reviewers, "before");
            const index = reviewers.indexOf(author);
            if (index > -1) {
              reviewers.splice(index, 1);
            }
            
            console.log(reviewers, "after");
