name: Merge Restrictions

on:
  pull_request:
    branches:
      - main

jobs:
  check-changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check for directory changes
        id: check_changes
        run: |
          echo "=============== Add your script/command here to check for directory changes ==============="
          # Add your script/command here to check for directory changes
          # For example:
          if git diff --name-only ${{ github.base_ref }}...${{ github.head_ref }} | grep -q "src/resources"; then
            echo "changes=true" >> $GITHUB_OUTPUT
          else
            echo "changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Add reviewers if directory changes detected
        if: steps.check_changes.outputs.changes == 'true'
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: reviewers } = await github.pulls.listRequestedReviewers({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            });
            if (!reviewers.some(reviewer => reviewer.login === 'username')) {
              await github.pulls.createReviewRequest({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.issue.number,
                reviewers: ['azamatus']
              });
            }
